### ISSUE TITLE
Help Me Please 

### ISSUE THREAD

**Issue by VahidZP** [sajadbz/WarehouseRemittance#11]
In frmOrderAddOrEdit  in part Edit please help me (Save Edit and Delete Product It does not work exactly)

**Comment by sajadbz** [comment]
I note some comments on OrderService and merge with master branch nut need check again by me.

**Comment by sajadbz** [comment]
I check the code and fixed some bugs, but it needs your debug and complete another thing.
I close this issue and you create another issue if you need my help.

**Comment by VahidZP** [comment]
Thanks
